services:
  postgresdb:
    image: postgres:15 # Hoặc dùng postgres:latest

  n8n:
    image: docker.n8n.io/n8nio/n8n  
    
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    
#network section
networks:
  default:
    name: psl-pfm-network
    driver: bridge
    
#volumes section
volumes:
  n8n_data: # Định nghĩa Docker volume tên là n8n_data
    name: n8n_data_test
  postgres_data: # Định nghĩa Docker volume mới cho Postgres
    name: postgres_data_test
 