version: '3.8' # Nên chỉ định phiên bản docker-compose

services:
  postgresdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: # Thêm network cho postgresdb để n8n có thể thấy
      - default

  n8n:
    image: docker.n8n.io/n8nio/n8n
    # build: # Nếu bạn có Dockerfile tùy chỉnh cho n8n, hãy giữ lại phần này
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    ports:
      - "${N8N_EXTERNAL_PORT}:5678"
    networks:
      - default
    volumes:
      - n8n_data:/home/node/.n8n
      - ./ssh:/home/node/.ssh
    depends_on: # n8n phụ thuộc vào postgresdb và redis
      postgresdb:
        condition: service_healthy # Chờ postgresdb sẵn sàng
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Asia/Ho_Chi_Minh}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresdb
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - EXECUTIONS_DATA_PRUNE=${EXECUTIONS_DATA_PRUNE:-true}
      - EXECUTIONS_DATA_MAX_AGE=${EXECUTIONS_DATA_MAX_AGE:-720}
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=${EXECUTIONS_DATA_PRUNE_MAX_COUNT:-50000}
      - N8N_DEFAULT_BINARY_DATA_MODE=${N8N_DEFAULT_BINARY_DATA_MODE:-filesystem}

  pfm_excel_api:
    build: 
      context: ./src
      dockerfile: ExcelApi/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS:-http://+:80}
      - TZ=${TZ:-Asia/Ho_Chi_Minh}
    ports:
      - "${EXCEL_API_HTTP_PORT}:80"
      - "${EXCEL_API_HTTPS_PORT}:443"
    networks:
      - default

#network section
networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  n8n_data:
