services:
  #postgresdb: postgresql database
  postgresdb:
    container_name: postgresdb # Tên container tùy chọn
    restart: always # Hoặc unless-stopped
    environment:
      # !!! QUAN TRỌNG: Nên sử dụng file .env cho các thông tin nhạy cảm này !!!
      POSTGRES_DB: n8n_database # Tên database sẽ được tạo tự động
      POSTGRES_USER: ${POSTGRES_USER}     # Tên user sẽ được tạo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # <--- THAY BẰNG MẬT KHẨU MẠNH CỦA BẠN
      # POSTGRES_HOST_AUTH_METHOD: trust # Chỉ dùng cho test, không an toàn!
    volumes:
      - postgresdb_data:/var/lib/postgresql/data # Map volume đã định nghĩa ở file kia
    ports:
      - "15432:5432" # Đổi cổng từ 15432 sang 25432 để tránh xung đột
    healthcheck: # Tùy chọn: kiểm tra sức khỏe DB
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 10s
        timeout: 5s
        retries: 5

  n8n:
    container_name: n8n_main  # Tên container tùy chọn
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n # Sử dụng Docker named volume thay vì bind mount
      - ./ssh:/home/node/.ssh # Mount thư mục .ssh từ host vào container
    depends_on:
      - postgresdb # Đảm bảo Postgres khởi động trước n8n
    environment:
      - TZ=Asia/Ho_Chi_Minh # Đặt múi giờ (quan trọng cho các trigger theo lịch)
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Asia/Ho_Chi_Minh} # Lấy từ .env hoặc dùng default
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      # -----------------------------------------

      # --- Cấu hình Database (PostgreSQL) ---
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresdb
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD} # Lấy từ .env
      # -----------------------------------------
      
      # --- Cấu hình Xác thực & Webhook ---
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true} # Giữ lại Basic Auth
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD} # Lấy từ .env (BẮT BUỘC NẾU ACTIVE=true)
      - WEBHOOK_URL=${WEBHOOK_URL:-} # Lấy từ .env hoặc để trống
      # -----------------------------------------

      # --- Cấu hình tùy chọn nên có ---
      - EXECUTIONS_DATA_PRUNE=${EXECUTIONS_DATA_PRUNE:-true} # Xóa dữ liệu cũ
      - EXECUTIONS_DATA_MAX_AGE=${EXECUTIONS_DATA_MAX_AGE:-720} # 7 ngày
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=${EXECUTIONS_DATA_PRUNE_MAX_COUNT:-50000} # Giới hạn số lượng bản ghi
      - N8N_DEFAULT_BINARY_DATA_MODE=${N8N_DEFAULT_BINARY_DATA_MODE:-filesystem} # Chế độ lưu trữ binary data
      # -----------------------------------------

  # Excel API service for processing Excel files
  pfm_excel_api:
    container_name: pfm_excel_api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - postgresdb
    networks:
      - default