services:
  postgresdb:
    image: postgres:15 # Hoặc dùng postgres:latest
    container_name: postgresdb # Sử dụng tên container gốc

  n8n:
    image: docker.n8n.io/n8nio/n8n  
    container_name: n8n_main # Sử dụng tên container gốc
    
  pfm_excel_api:
    build: 
      context: ./src
      dockerfile: ExcelApi/Dockerfile
    container_name: pfm_excel_api
    
#network section
networks:
  default:
    name: n8n-network
    driver: bridge
    
#volumes sect    external: true # Đánh dấu network là external để sử dụng network hiện có
    
#volumes section
volumes:
  n8n_data: 
    # Bỏ external: true để Docker tự tạo volume nếu chưa tồn tại
    name: n8n_data
  postgresdb_data: 
    # Bỏ external: true để Docker tự tạo volume nếu chưa tồn tại
    name: postgresdb_data