# Cấu hình Cloudflare Tunnel để quản lý nhiều endpoint
# Trong đó bao gồm: n8n web interface và SSH

# Tunnel sẽ sử dụng token từ biến môi trường
tunnel: ${CLOUDFLARE_TUNNEL_TOKEN}
credentials-file: /etc/cloudflared/credentials.json

# Ghi log vào stdout để Docker có thể xử lý
logfile: /dev/stdout

# Định nghĩa các ingress rules (các endpoint sẽ được public ra internet)
ingress:
  # Đường dẫn đến n8n web interface - đọc từ biến môi trường
  - hostname: ${N8N_DOMAIN}
    service: http://n8n:5678
    originRequest:
      noTLSVerify: true

  # Endpoint SSH qua Cloudflare - đọc từ biến môi trường
  - hostname: ${SSH_DOMAIN}
    service: ssh://host.docker.internal:22
    originRequest:
      noTLSVerify: true

  # Catch-all rule, để đảm bảo bất kỳ traffic không khớp nào cũng được từ chối
  - service: http_status:404